
FROM ubuntu:16.04

RUN mkdir /code
WORKDIR /code
ADD . /code/

RUN apt-get update && apt-get install -y --no-install-recommends \
        openmpi-bin \
        python3 \ 
        python3-dev \ 
        python3-setuptools \
        python3-pip && \
    pip3 install -r /code/requirements.txt

EXPOSE 5000

ENTRYPOINT ["python3"]
CMD ["app.py"]